import React from 'react';
import { Helmet } from 'react-helmet';
import { AlertTriangle } from 'lucide-react';
import Header from '@/components/Header.jsx';
import Footer from '@/components/Footer.jsx';

const DisclaimerPage = () => {
  return (
    <>
      <Helmet>
        <title>Disclaimer - GTrends Network</title>
        <meta name="description" content="Legal and financial disclaimers for GTrends Network." />
      </Helmet>

      <div className="min-h-screen bg-background text-foreground flex flex-col">
        <Header />

        <main className="flex-1 py-20">
          <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="flex items-center gap-4 mb-10 pb-10 border-b border-border">
              <div className="w-16 h-16 rounded-2xl bg-destructive/10 flex items-center justify-center flex-shrink-0">
                <AlertTriangle className="w-8 h-8 text-destructive" />
              </div>
              <div>
                <h1 className="text-4xl font-extrabold tracking-tight">Legal Disclaimer</h1>
                <p className="text-muted-foreground mt-2">Important information regarding our tools and services</p>
              </div>
            </div>

            <div className="prose prose-invert max-w-none prose-headings:text-foreground prose-p:text-muted-foreground prose-a:text-primary prose-strong:text-foreground">
              <h2>Not Financial or Professional Advice</h2>
              <p>
                <strong>GTrends Network is not a bank, brokerage, licensed financial advisor, or legal firm.</strong> All information, tools, calculators, and content published on this website are provided strictly for educational and informational purposes. 
              </p>
              <p>
                None of the materials presented on GTrends Network should be construed as personalized financial planning, investment advice, legal counsel, or tax advice. We strongly recommend that you consult with certified professionals—such as a registered investment advisor, CPA, or legal counsel—before making any significant financial decisions.
              </p>

              <h2>Estimates and Market Data</h2>
              <p>
                The financial projections generated by our tools (e.g., compound interest estimates, business margins, or credit card reward values) are hypothetical and rely on generalized market assumptions. They do not account for individual tax situations, changing inflation rates, sudden market downturns, or hidden third-party fees.
              </p>
              <p>
                Past performance of any asset class or strategy discussed on our platform is not indicative of future results. GTrends Network accepts no liability for the accuracy of these calculations or the real-world outcomes resulting from their application.
              </p>

              <h2>Affiliate Relationships</h2>
              <p>
                GTrends Network partners with various financial institutions, e-commerce platforms, and service providers. This means that if you click on a referral link and subsequently purchase a product or sign up for a service, we may earn an affiliate commission at no additional cost to you.
              </p>
              <p>
                While we strive to curate high-quality resources, we do not endorse or guarantee the performance of any third-party products. Users must conduct their own due diligence before entering into agreements with external providers.
              </p>

              <h2>No Liability</h2>
              <p>
                Your reliance on any information provided by GTrends Network is solely at your own risk. We disclaim all liability for any direct, indirect, incidental, or consequential damages resulting from your use of the website or the implementation of any strategies discussed herein.
              </p>

              <h2>Contact Us</h2>
              <p>
                If you have questions about this disclaimer, please contact us at:
              </p>
              <p>
                <strong>Email:</strong> <a href="mailto:contact@gtrendsnow.com">contact@gtrendsnow.com</a>
              </p>
            </div>
          </div>
        </main>

        <Footer />
      </div>
    </>
  );
};

export default DisclaimerPage;