import React from 'react';
import { Helmet } from 'react-helmet';
import { BookText } from 'lucide-react';
import Header from '@/components/Header.jsx';
import Footer from '@/components/Footer.jsx';

const TermsOfServicePage = () => {
  return (
    <>
      <Helmet>
        <title>Terms of Service - GTrends Global</title>
        <meta name="description" content="Terms of Service and user agreement for GTrends Global financial research platform." />
      </Helmet>

      <div className="min-h-screen bg-background text-foreground flex flex-col">
        <Header />

        <main className="flex-1 py-20">
          <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="flex items-center gap-4 mb-10 pb-10 border-b border-border">
              <div className="w-16 h-16 rounded-2xl bg-secondary/10 flex items-center justify-center flex-shrink-0">
                <BookText className="w-8 h-8 text-secondary" />
              </div>
              <div>
                <h1 className="text-4xl font-extrabold tracking-tight">Terms of Service</h1>
                <p className="text-muted-foreground mt-2">Effective Date: May 6, 2026</p>
              </div>
            </div>

            <div className="prose prose-invert max-w-none prose-headings:text-foreground prose-p:text-muted-foreground prose-a:text-primary prose-strong:text-foreground">
              <h2>1. Acceptance of Terms</h2>
              <p>
                By accessing, browsing, or using the GTrends Global website and its associated tools, calculators, and research materials (collectively, the "Platform"), you acknowledge that you have read, understood, and agree to be bound by these Terms of Service. If you do not agree with any part of these terms, you must not use our Platform.
              </p>

              <h2>2. Platform Nature and Disclaimers</h2>
              <p>
                <strong>GTrends Global is a financial research and educational platform, not a registered investment advisor, broker-dealer, or financial institution.</strong>
              </p>
              <ul>
                <li><strong>No Financial Advice:</strong> The content, calculators, and insights provided on this Platform are for informational and educational purposes only. They do not constitute professional financial, investment, legal, or tax advice.</li>
                <li><strong>Market Data Disclaimer:</strong> While we strive to provide accurate and up-to-date information, financial markets are highly volatile. We make no representations or warranties regarding the accuracy, completeness, or timeliness of any market data, projections, or calculations provided.</li>
                <li><strong>No Guarantees:</strong> Past performance is not indicative of future results. Any financial projections generated by our tools are hypothetical estimates based on user inputs and generalized market assumptions.</li>
              </ul>
              <p>You are solely responsible for your own financial decisions. We strongly recommend consulting with a qualified, licensed financial professional before making any investment or business decisions.</p>

              <h2>3. User Conduct and Responsibilities</h2>
              <p>As a user of GTrends Global, you agree to use the Platform responsibly and lawfully. You strictly agree NOT to:</p>
              <ul>
                <li>Use the Platform for any illegal, fraudulent, or unauthorized purpose.</li>
                <li>Attempt to interfere with, compromise the system integrity or security, or decipher any transmissions to or from the servers running the Platform.</li>
                <li>Use automated scripts, spiders, robots, or scrapers to harvest data, content, or proprietary algorithms from the Platform.</li>
                <li>Submit false, misleading, or malicious data through our forms or calculators.</li>
                <li>Reproduce, duplicate, copy, sell, or exploit any portion of the Platform without express written permission from GTrends Global.</li>
              </ul>

              <h2>4. Intellectual Property</h2>
              <p>
                All content, features, functionality, algorithms, calculators, text, graphics, logos, and software on the Platform are the exclusive property of GTrends Global and are protected by international copyright, trademark, patent, trade secret, and other intellectual property or proprietary rights laws. You are granted a limited, non-exclusive, non-transferable license to access and use the Platform for personal, non-commercial purposes.
              </p>

              <h2>5. Limitation of Liability</h2>
              <p>
                To the maximum extent permitted by applicable law, in no event shall GTrends Global, its founders, directors, employees, or partners be liable for any indirect, punitive, incidental, special, consequential, or exemplary damages, including without limitation damages for loss of profits, goodwill, use, data, or other intangible losses, arising out of or relating to the use of, or inability to use, the Platform.
              </p>
              <p>
                Under no circumstances will GTrends Global be responsible for any damage, loss, or injury resulting from hacking, tampering, or other unauthorized access or use of the Platform or your account.
              </p>

              <h2>6. Third-Party Links and Services</h2>
              <p>
                Our Platform may contain links to third-party websites, advertisers, services, or special offers that are not owned or controlled by GTrends Global. We do not endorse or assume any responsibility for any such third-party sites, information, materials, products, or services. Your dealings with third-party entities found on the Platform are solely between you and such entities.
              </p>

              <h2>7. Governing Law and Dispute Resolution</h2>
              <p>
                These Terms shall be governed by and construed in accordance with the laws of the jurisdiction in which GTrends Global is established, without regard to its conflict of law provisions. Any dispute arising from or relating to the subject matter of these Terms shall be finally settled by binding arbitration in accordance with recognized commercial arbitration rules, except that either party may seek injunctive or equitable relief in a court of competent jurisdiction.
              </p>

              <h2>8. Contact Information</h2>
              <p>
                If you have any questions about these Terms of Service, please contact us at:
              </p>
              <p>
                <strong>Email:</strong> legal@gtrendsglobal.com
              </p>
            </div>
          </div>
        </main>

        <Footer />
      </div>
    </>
  );
};

export default TermsOfServicePage;